from __future__ import annotations

import argparse
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

import pandas as pd

from src.generator import GeneratorConfig


# Configuration — The reference values for ‘valid’ are generated by the generator,
# to ensure that the generator and the data quality layer remain synchronised.

@dataclass
class DataQualityConfig:
    min_amount: float = 0.01
    max_amount: float = 500_000.0  # deliberately set above normal amounts; purely a plausibility threshold

    valid_accounts: tuple[str, ...] = field(default_factory=lambda: GeneratorConfig().accounts)
    valid_contra_accounts: tuple[str, ...] = field(default_factory=lambda: GeneratorConfig().contra_accounts)
    valid_currencies: tuple[str, ...] = field(default_factory=lambda: GeneratorConfig().currencies)
    valid_cost_centers: tuple[str, ...] = field(default_factory=lambda: GeneratorConfig().cost_centers)
    valid_payment_types: tuple[str, ...] = field(default_factory=lambda: GeneratorConfig().payment_types)

    date_min: datetime = field(default_factory=lambda: GeneratorConfig().start_date)
    date_max: datetime = field(default_factory=lambda: GeneratorConfig().end_date)


CHECK_NAMES = [
    "check_completeness",
    "check_not_duplicate",
    "check_valid_date",
    "check_valid_amount",
    "check_valid_accounts",
    "check_field_consistency",
]


# Checker

class DataQualityChecker:
    def __init__(self, config: DataQualityConfig | None = None) -> None:
        self.config = config or DataQualityConfig()


    def check_completeness(self, df: pd.DataFrame) -> pd.Series:
        """Uses the flag calculated by etl.py, if available."""
        if "has_missing_required_field" in df.columns:
            return ~df["has_missing_required_field"].astype(bool)
        required = ["account", "amount", "cost_center", "clerk", "booking_datetime"]
        return ~df[required].isna().any(axis=1)

    def check_not_duplicate(self, df: pd.DataFrame) -> pd.Series:
        """Uses the flag calculated by etl.py, if available."""
        if "is_potential_duplicate" in df.columns:
            return ~df["is_potential_duplicate"].astype(bool)
        return pd.Series(True, index=df.index)

    def check_valid_date(self, df: pd.DataFrame) -> pd.Series:
        dt = pd.to_datetime(
            df["booking_datetime"],
            errors="coerce",
            format="mixed",
        )

        min_date = pd.Timestamp(self.config.date_min).date()
        max_date = pd.Timestamp(self.config.date_max).date()

        return (
            dt.notna()
            & (dt.dt.date >= min_date)
            & (dt.dt.date <= max_date)
        )

    def check_valid_amount(self, df: pd.DataFrame) -> pd.Series:
        amount = pd.to_numeric(df["amount"], errors="coerce")
        return amount.notna() & (amount >= self.config.min_amount) & (amount <= self.config.max_amount)

    def check_valid_accounts(self, df: pd.DataFrame) -> pd.Series:
        account_ok = df["account"].astype("string").isin(self.config.valid_accounts)
        contra_ok = df["contra_account"].astype("string").isin(self.config.valid_contra_accounts)
        return account_ok & contra_ok

    def check_field_consistency(self, df: pd.DataFrame) -> pd.Series:
        account_neq_contra = df["account"].astype("string") != df["contra_account"].astype("string")
        currency_ok = df["currency"].astype("string").isin(self.config.valid_currencies)
        cost_center_ok = df["cost_center"].astype("string").isin(self.config.valid_cost_centers)
        payment_type_ok = df["payment_type"].astype("string").isin(self.config.valid_payment_types)
        return account_neq_contra & currency_ok & cost_center_ok & payment_type_ok


    def run_checks(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        for check_name in CHECK_NAMES:
            check_fn = getattr(self, check_name)
            df[check_name] = check_fn(df)

        df["dq_checks_passed"] = df[CHECK_NAMES].sum(axis=1)
        df["dq_row_score"] = df["dq_checks_passed"] / len(CHECK_NAMES)
        df["dq_passes_all_checks"] = df["dq_checks_passed"] == len(CHECK_NAMES)
        return df

    def summarize(self, df: pd.DataFrame) -> dict:
        summary = {
            "run_timestamp": datetime.now().isoformat(timespec="seconds"),
            "total_rows": len(df),
            "overall_score_pct": round(df["dq_row_score"].mean() * 100, 2),
            "rows_passing_all_checks_pct": round(df["dq_passes_all_checks"].mean() * 100, 2),
        }
        for check_name in CHECK_NAMES:
            summary[f"{check_name}_pass_rate_pct"] = round(df[check_name].mean() * 100, 2)
        return summary


# I/O

def load_from_db(db_path: str | Path, table_name: str) -> pd.DataFrame:
    with sqlite3.connect(db_path) as conn:
        return pd.read_sql(f"SELECT * FROM {table_name}", conn)


def append_summary_log(summary: dict, log_path: str | Path) -> None:
    log_path = Path(log_path)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    summary_df = pd.DataFrame([summary])
    if log_path.exists():
        summary_df.to_csv(log_path, mode="a", header=False, index=False)
    else:
        summary_df.to_csv(log_path, mode="w", header=True, index=False)


# CLI

def run_data_quality(
    db_path: str | Path,
    table_name: str = "transactions_clean",
    summary_log_path: str | Path = "data/processed/dq_score_history.csv",
    config: DataQualityConfig | None = None,
) -> dict:
    df = load_from_db(db_path, table_name)
    checker = DataQualityChecker(config)
    df = checker.run_checks(df)
    summary = checker.summarize(df)

    append_summary_log(summary, summary_log_path)

    print(f"Data-Quality-Score dieses Laufs: {summary['overall_score_pct']}%")
    print(
        f"Zeilen ohne jeden Verstoß: "
        f"{summary['rows_passing_all_checks_pct']}%"
    )

    for check_name in CHECK_NAMES:
        print(
            f"  {check_name}: "
            f"{summary[f'{check_name}_pass_rate_pct']}% bestanden"
        )

    return summary


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Data-Quality-Prüfungen auf ETL-Ergebnis")
    parser.add_argument("--db", type=str, default="data/processed/transactions.db")
    parser.add_argument("--table", type=str, default="transactions_clean")
    parser.add_argument("--summary-log", type=str, default="data/processed/dq_score_history.csv")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    run_data_quality(args.db, args.table, args.summary_log)


if __name__ == "__main__":
    main()
